version: "3"
services:
  geo-app:
    build:
      context: .
      dockerfile: app/geo/Dockerfile
    container_name: geo-app
    stdin_open: true
  twks-server:
    container_name: twks-server
    image: tetherlessworld/twks-server
    ports:
      - 127.0.0.1:8080:8080
