version: "3"
services:
  geo-app:
    build:
      context: .
      dockerfile: app/geo/Dockerfile
    container_name: geo-app
    stdin_open: true
    ports:
      - 127.0.0.1:8081:80
  twks-server:
    container_name: twks-server
    deploy:
      resources:
        limits:
          memory: 4g
    environment:
      JAVA_OPTIONS: "-Dtwks.extcp=/extcp -Dtwks.dump=/dump -Dtwks.extfs=/extfs -Dtwks.initialNanopublicationFilePath=/geo-data/loaded/reverse_beacon/features.ttl.bz2,/geo-data/loaded/tiger_line/features.ttl.bz2,/geo-data/loaded/uls/features.ttl.bz2 -Dtwks.tdbLocation=/data"
    image: tetherlessworld/twks-server
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./data/geo:/geo-data:ro
